[APP]
TENSORBOARD_DIR = "tensorboard"
OUTPUT_DIR = "out"
SAVE_STEPS = 1000

# MODEL_NAME = "model_20240728-182541_final.pt"
MODEL_NAME = "model_20240729-084354_e4000.pt"

[LOG]
LEVEL = "INFO"

[MODEL]

LR = 1e-4
GAMMA = 0.95
INITIAL_GAMMA = 0.0
GAMMA_RAMP_STEPS = 1000
GRAD_STEPS = 8
DECAY = 0.998
MIN_EPSILON = 0.1
CLIP_GRAD = 1.0

[STOCKFISH]

PATH = "/Users/johnmccain/Documents/repos/rl-chess/stockfish/stockfish-macos-m1-apple-silicon"
