[APP]
TENSORBOARD_DIR = "tensorboard"
OUTPUT_DIR = "out"
SAVE_STEPS = 2000
EVAL_STEPS = 500
MOVE_EVAL_DATASET = "fen_validation_dataset.csv"

# MODEL_NAME = "model_20240728-182541_final.pt"
MODEL_NAME = "model_20240808-165625_e36096.pt"

[LOG]
LEVEL = "INFO"

[MODEL]

LR = 1e-4
GAMMA = 0.9
INITIAL_GAMMA = 0.0
GAMMA_STARTUP_STEPS = 25000
GAMMA_RAMP_STEPS = 200000
GRAD_STEPS = 8
DECAY = 0.998
MIN_EPSILON = 0.1
CLIP_GRAD = 1.0
MAX_MOVES = 100
BUFFER_SIZE = 200000
BATCH_SIZE = 64
EXPLORE_EPISODES = 3
LEARN_STEPS = 2000
TARGET_UPDATE_FREQ = 1000
NUM_FILTERS = 256
RESIDUAL_BLOCKS = 12

[STOCKFISH]

# PATH = "/Users/johnmccain/Documents/repos/rl-chess/stockfish/stockfish-macos-m1-apple-silicon"
PATH = "C:/Users/John/Documents/repos/rl-chess/stockfish/stockfish-windows-x86-64-avx2.exe"
PROB = 0.15
DEPTH = 10
