[APP]
TENSORBOARD_DIR = "tensorboard"
OUTPUT_DIR = "out"
SAVE_STEPS = 2000
EVAL_STEPS = 2000
MOVE_EVAL_DATASET = "fen_validation_dataset.csv"

# MODEL_NAME = "model_20240728-182541_final.pt"
# MODEL_NAME = "pretrained_EnsembleCNNTransformer_20240918004514_final.pkl"
# MODEL_NAME = "model_20240917-184532_e26624.pt"
MODEL_NAME = "model_20240921-084810_e403456.pt"
CHECKMATE_REWARD = 10.0
TURN_PENALTY = -0.05

[LOG]
LEVEL = "INFO"

[MODEL]

CLASS = "EnsembleCNNTransformer"

LR = 1e-4
WARMUP_STEPS = 2000
BATCH_SIZE = 64
GRAD_STEPS = 8  # Unused
CLIP_GRAD = 1.0

GAMMA = 0.9
INITIAL_GAMMA = 0.0
GAMMA_STARTUP_STEPS = 10000
GAMMA_RAMP_STEPS = 100000
DECAY = 0.998
MIN_EPSILON = 0.2
MAX_MOVES = 200
EXPLORE_EPISODES = 2
LEARN_STEPS = 2000
BUFFER_SIZE = 200000
TARGET_UPDATE_FREQ = 1000

[MODEL.CNN]
NUM_FILTERS = 128
RESIDUAL_BLOCKS = 4
NEGATIVE_SLOPE = 0.0
DROPOUT = 0.1

[MODEL.TRANSFORMER]
D_MODEL=128
NUM_HEADS=4
NUM_LAYERS=4
DIM_FEEDFORWARD=512
DROPOUT=0.1
FREEZE_POS=false # Freeze positional encoding
ADD_GLOBAL=false # Add global token

[STOCKFISH]

# PATH = "/Users/johnmccain/Documents/repos/rl-chess/stockfish/stockfish-macos-m1-apple-silicon"
PATH = "C:/Users/John/Documents/repos/rl-chess/stockfish/stockfish-windows-x86-64-avx2.exe"
PROB = 0.15
DEPTH = 6
BLUNDER_THRESHOLD = 100 # centipawns
