[APP]
TENSORBOARD_DIR = "tensorboard"
OUTPUT_DIR = "out"
SAVE_STEPS = 500

MODEL_NAME = "model_20240728-182541_final.pt"

[LOG]
LEVEL = "INFO"

[MODEL]

LR = 1e-5
GAMMA = 0.0
INITIAL_GAMMA = 0.0
GAMMA_RAMP_STEPS = 2000
GRAD_STEPS = 8
DECAY = 0.995
CLIP_GRAD = 1.0
